spring.application.name=checkout-service-java
# Run the Java service on port 8080 so it doesn't clash with Node.js on port 5001
server.port=8080

# Connect to the exact same MongoDB database your Node.js app is using
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/swift_ecommerc